image: maven:3.6.3-jdk-11

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &buildAndTestSonarCloud
            name: Analyze with SonarCloud
            caches:
              - node
              - sonar
            script:
              - npm update && npm install  
              - pipe: sonarsource/sonarcloud-scan:1.1.0
                SONAR_TOKEN: '7c893ed1238413656ea7b997f0f3381dc32d4118'
                EXTRA_ARGS: '-Dsonar.sources=src/app'
                SONAR_SCANNER_OPTS: -Xmx512m
                DEBUG: "false"

pipelines:                 # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    master:
      - step: *build-test-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud